# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./", "/vagrant", disabled: false
  config.vm.provision "build-env", type: "shell", :path => "./scripts/build-env.sh", privileged: false
  config.vm.provision "build-image", type: "shell", :run => 'always', :path => "./scripts/build-image.sh", privileged: false, env: {"PACKERFILE" => ENV["PACKERFILE"]}
end
